### ISSUE TITLE
[Bug] Cannot Cancel Mesh Validation Pattern (6.2.2)

### ISSUE THREAD

**Issue by ckarcz** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#11]
- Can't cancel mesh validation pattern print on the printer UI
----
- MB firmware: [main_board_LA_IS_7x7.zip](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2/releases/download/Vyper-CE-6.2.2/main_board_LA_IS_7x7.zip) | [Vyper-CE-6.2.2](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2/releases/tag/Vyper-CE-6.2.2)
- LCD firmware: [Vyper-CE-6.2.2-Touchscreen-2024-04-02.zip](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/releases/download/Vyper-CE-6.2.2/Vyper-CE-6.2.2-Touchscreen-2024-04-02.zip) | [Release Vyper-CE-6.2.2](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/releases/tag/Vyper-CE-6.2.2)

**Comment by rommulaner** [comment]
Yes, that's a known issue, but it's not related to the CE firmware. It's a general issue of Marlin, it's not possible to cancel a the G26 command.
