### ISSUE TITLE
bricked screen with v4.7 

### ISSUE THREAD

**Issue by protocold** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#12]
I have tried to follow the instructions to flash 6.2.2 LCD firmware onto my Vyper screen [DMG80480C043_02WTRZ07], which apparently on V4.7 and it did not work, I have the following observations

1. it will not downgrade to V3.5 no matter what I tried, even with the T5L_OS file. 
2. The screen was unresponsive and the calibration cfg included in the release did not work on this screen.
3. I eventually came across this version of calibration cfg from Creality CR6 Community which seems to support v4.5+ and it seems to fix the calibration issue:
 https://github.com/CR6Community/CR-6-touchscreen/tree/extui/docs/build/Release%20Candidate_26_April_2022_v2/FOR%20DEVELOPERS%20AND%20TESTERS%20ONLY

4. However, with the new calibration, 6.2.2 LCD firmware only works for a short while before the screen turn black and won't turn on again, somehow the firmware is corrupted. **This corruption is reproducible.** 
5. I actually tried to flash the firmware CR6 re-factored 1.1 (https://github.com/CR6Community/CR-6-touchscreen/releases/tag/Re-Factored_v1.1) on this screen and it seems to work ok without the black screen and corruption, but of course it is now stuck in 272x480 with usable screen size around 1/4 of the whole screen (480x800).

Does anyone have similar problem with screen that is on V4.7?
Is it safe to use mainboard firmware 6.2.2 with this CR6 re-factored 1.1?

**Comment by rommulaner** [comment]
Have you copied both OS bin files on the sd card?

**Comment by protocold** [comment]
yes, only 2 OS bin inside DSET_SET. is it the right way?

**Comment by rommulaner** [comment]
No, you should add these 2 OS bin files to the other files in the DWIN_SET folder.

**Comment by protocold** [comment]
Oh, so the full step should then be:

1) flash reset
2) copy the firmware dwin_set file onto sdcard
3) add the 2 OS bin into the same dwin_set
4) flash again

Just want to confirm as I have obviously misunderstood before.

**Comment by rommulaner** [comment]
The reset is not mandatory but also not wrong. Yes try it like this.

**Comment by protocold** [comment]
tried. It doesn't work... just blank screen (backlight seems to be coming on and off in a dim way)

**Comment by rommulaner** [comment]
Please post a picture of the finished flash screen.

**Comment by protocold** [comment]
I figured it out.. I managed to downgrade to V3.5 but not with the instructions above. What works for me was the downgrade instruction in this YouTube for CR6: https://www.youtube.com/watch?v=0xwFGiyg4Z8

But first I have to use the V4.5 file to downgrade from V4.7 to V4.5, then further downgrade from V4.5 to V3.5 with V3.5 file(direct downgrade from V4.7 to V3.5 didn't work). Each time I only put one of the bin inside DWIN_SET and nothing else.. if downgrade is successful, then I see red word overlapping white word on the top line as seen in the video.

https://github.com/CR6Community/CR-6-touchscreen/tree/extui/docs/build/Release%20Candidate_26_April_2022_v2/DGUS2%20kernel%20upgrade%20files

Once I downgraded to V3.5, then I flash your reset and then can follow your original instruction of flashing the Vyper LCD firmware, then do the calibration cfg, touch the 4 corners and I am now good to go.

**Comment by rommulaner** [comment]
Great to hear! Can you share the files from 4.7 and 4.5 here?

**Comment by protocold** [comment]
I did above ^^^^ , here it is again:

https://github.com/CR6Community/CR-6-touchscreen/tree/extui/docs/build/Release%20Candidate_26_April_2022_v2/DGUS2%20kernel%20upgrade%20files

there are 2 files, V45 and V35.

**Comment by rommulaner** [comment]
Release is updated and should now be easier to handle.
