### ISSUE TITLE
Must keep SD card in reader on every startup

### ISSUE THREAD

**Issue by Zephyrus67** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#2]
After flashing my vyper to this project (6.1d on both screen and mainboard) I need to keep the sd card in the mainboard to be able to startup...I guess it reads and installs the firmware everytime this way..

If I pull out the card and turns the printer off and on, then it gets stuck on the screen loading with the process bar all green.

**Comment by rommulaner** [comment]
There are 3 hidden buttons on the start screen, upper edge, center on box and lower edge, for reset, main menu and firmware update. Try them if it helps.

**Comment by Zephyrus67** [comment]
Thank you for getting back this quick. I actually tried resetting to factory default and remove the card..then turn off and on..that worked.....but another issue was there as well.

Every now and then (not sure if it was only in certain pages) the screen was flashing (like it was maybe drawing a page firts and then went on fast to the correct page. I dont have that problem with the 6.1c project I am playing with also.

**Comment by rommulaner** [comment]
That is curious, because the screen firmware is nearly the same but config could maybe be not suitable for your version and can cause that issue.
I only made some positioning of some text fields because of misalignment and something like that.
