### ISSUE TITLE
Problem mit dem Display

### ISSUE THREAD

**Issue by SvenBornemann81** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#3]
Hi,

habe alles wie beschrieben installiert aber leider kommt beim Hochfahren diese Meldung
![Display Fail](https://user-images.githubusercontent.com/123616380/215346111-b05a1147-c5f5-42ad-a102-e7688dd16e83.jpg)

**Comment by rommulaner** [comment]
Was zeigte der blaue Bildschirm nach dem Flashen an?
Mainboard ist auch geflasht?

**Comment by SvenBornemann81** [comment]
![IMG20230129191158](https://user-images.githubusercontent.com/123616380/215413652-81d0e6fd-9e77-48d3-8ebc-80eab51ecd7e.jpg)

**Comment by rommulaner** [comment]
Sieht ja soweit ganz gut aus.
Hat das Mainboard auch erfolgreich geflasht? Blinkt und piept danach?

**Comment by SvenBornemann81** [comment]
Ja die LED hat beleuchtet und es hat 5x gepiept.

Sry wenn ich immer solange brauche zum antworten, bin noch bis 16:00 Uhr auf der Arbeit. 

Habe erstmal alles wieder in den original Zustand gebracht. Kann es vllt an einer Datei von dir liegen oder so?

**Comment by SvenBornemann81** [comment]
Ja die LED hat beleuchtet und es hat 5x gepiept.

Habe erstmal alles wieder auf original zurück gemacht bis es eine Lösung gibt 😉

**Comment by rommulaner** [comment]
Auf dem Bootbildschirm kannst ja mal in den oberen Bereich tippen, da ist ein versteckter Button. Ebenso wie unten. Die sind für Reset und Firmwareupdate. Auf dem Würfel kommst ins Hauptmenü.

**Comment by SvenBornemann81** [comment]
Meinst du jetzt beim Original? 
Habe ja geschrieben das ich dann gestern kein Bock mehr hatte, und habe erstmal alles (Board, Display) wieder auf original gemacht. Also jetzt Version 2.4.5 meine ich 🤔

**Comment by SvenBornemann81** [comment]
So habe jetzt erst das Display dann das Mainboard geflasht.
Resultat, siehe Anhang.
Bild 1 - Daten nach dem Flash
Bild 2 & 3 - Boot
Bild 4 - Touch funktioniert nicht und kommt auch nur zu dem Bildschirm wenn die SD Karte (Board)
im Drucker steckt

![IMG20230131183601](https://user-images.githubusercontent.com/123616380/215840679-20acf58a-f5da-4f86-8f45-53d67fb0c225.jpg)
![IMG20230131183626](https://user-images.githubusercontent.com/123616380/215840707-d1a696bd-e10c-47ee-82de-4e185edcfce9.jpg)
![IMG20230131183655](https://user-images.githubusercontent.com/123616380/215840742-d78e270f-3e4a-4d26-b4d8-c054e3c40f02.jpg)
![Uploading IMG20230131183720.jpg…]()

**Comment by SvenBornemann81** [comment]
![Uploading IMG20230131183720.jpg…]()

**Comment by rommulaner** [comment]
Sieht so aus als würde das Mainboard nicht korrekt geflasht werden oder der Reset fehlen. Verbinde den Drucker mal mit dem PC und versuche mit pronterface mal ob er sich ansprechen lässt und ob M502 funktioniert.

Welche Version ist der Drucker?

**Comment by SvenBornemann81** [comment]
![16751885840882346326821841516250](https://user-images.githubusercontent.com/123616380/215846560-08ecdf2f-69b2-4c73-a8fe-ba61af799e42.jpg)

**Comment by SvenBornemann81** [comment]
![1675188680394755960210531333116](https://user-images.githubusercontent.com/123616380/215846869-83f1fcde-5ae3-45f0-9f6b-044b381dba86.jpg)


Das zeigt er aktuell, aber der Touch funktioniert nicht

**Comment by SvenBornemann81** [comment]
![16751889961692245411689019497205](https://user-images.githubusercontent.com/123616380/215847886-c581fd4b-541b-46ac-9495-da11a340922b.jpg)


Das die BIN die ich drauf gemacht habe

**Comment by rommulaner** [comment]
Sieht doch schon besser aus. Ich denke du musst noch das Display kalibrieren, bzw. Du kannst auch mal versuchen die CFG Datei fürs Display durch die Originale zu ersetzen und neu zu Flashen.

**Comment by SvenBornemann81** [comment]
![16751897630816818825109782891616](https://user-images.githubusercontent.com/123616380/215850382-1262fcfa-645e-4fc1-b0e0-dce079c09e05.jpg)


Und die Nozzle LED blinkt.

Das war jetzt die originale cfg

**Comment by SvenBornemann81** [comment]
Sry für die ganzen unannämlichkeiten, hoffe das ich dich nicht nerve, aber verstehe echt nicht woran es liegt.

**Comment by rommulaner** [comment]
Ich versuche zu helfen wo ich kann, ein Vollprofi darin bin ich sicherlich nicht.
Musst mal googlen wie man das Display kalibriert, dann sollte es funktionieren. Es gibt auch einen Ami in der Facebook Gruppe der das so gemacht hat.
Lad dir mal die Firmware von der 6.1B aufs Display und dann die 6.1D, hat bei einigen funktioniert.

**Comment by SvenBornemann81** [comment]
Ich finde es ja auch total nett von dir, das du mich da unterstützt, bin echt am verzweifeln langsam.

Und wieder eine Blöde Frage, wo finde ich die 6.1B Version?

**Comment by rommulaner** [comment]
Hier hab ich was gefunden:

https://www.3dfd.de/vyper-firmware/

**Comment by SvenBornemann81** [comment]
So danke dir viel vielmals, er läuft jetzt

**Comment by rommulaner** [comment]
Hat es mit der 6.1b geklappt oder lag es an was anderes?

**Comment by SvenBornemann81** [comment]
Habe das hier gemacht, war bevor du geschrieben hast


https://www.reddit.com/r/AnycubicVyper/comments/ssteu9/community_edition_v61c_firmware_for_anycubic/

**Comment by SvenBornemann81** [comment]
sry, das hier war es

https://www.reddit.com/r/anycubic/comments/vapmec/comment/iq5xliw/?utm_source=share&utm_medium=web2x&context=3


https://drive.google.com/drive/folders/1Wc5taL6-R2K7oSruxMQwYWXxCWx3tLiT
