### ISSUE TITLE
LCD Firmware seems flashed correctly but no touch

### ISSUE THREAD

**Issue by Gman1988** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#4]
Hi team, just flashed LCD firmware to Anycubic Vyper with your custom firmware and it seems everything went well, after reboot screen shows up and react when I operate with printer using OctoPrint but doesn't react on touch.

I tried with 3 different brand and size sd cards and result seems to be the same. 

Any suggestions ?

Thnaks,
Paweł
![PXL_20240205_193119024 MP](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/assets/13338697/ec167a0b-8fe1-4ff0-a86f-382860d6781b)

**Comment by rommulaner** [comment]
What version did you use before?

**Comment by Gman1988** [comment]
> What version did you use before?

Previously I used stock firmware. 

From stock I moved to [Anycubic_Vyper_MB_CE_6.2](https://github.com/rommulaner/Anycubic_Vyper_MB_CE_6.2) then followed this guide on [Anycubic_Vyper_LCD_CE_6.2](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/tree/main/src)

**Comment by rommulaner** [comment]
Then you need to flash the touch calibration config and calibrate the touch. It's all described in the release notes of the LCD.

**Comment by Gman1988** [comment]
> Then you need to flash the touch calibration config and calibrate the touch. It's all described in the release notes of the LCD.

Ahh now I see, I could not find[ 6.2.1 release notes](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/releases/tag/Vyper-CE-6.2.1) :) I will try again

**Comment by rommulaner** [comment]
https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/releases/tag/Vyper-CE-6.2.1

**Comment by Gman1988** [comment]
> https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/releases/tag/Vyper-CE-6.2.1

Worked like a charm,  I apologize for not doing enough searching :) Thanks for being patient!

**Comment by rommulaner** [comment]
No problem, nice to hear it's working as it should.
