### ISSUE TITLE
TMC Settings

### ISSUE THREAD

**Issue by trashmaster9000** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#5]
Hello,

found a secret / hidden menu in axis setup menu

if i tap a bit above the nozzle temperature a new screen "TMC Settings" appears, see attached photos

![2024-02-12-18-13-17-755](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/assets/14186848/a34bfd7d-4920-4bdb-872b-984df0300cd7)
![2024-02-12-18-12-35-923](https://github.com/rommulaner/Anycubic_Vyper_LCD_CE_6.2/assets/14186848/3c5ecfe3-1998-4d4e-8072-55531abb5cf5)

**Comment by rommulaner** [comment]
Yes, that's the TMC Setup menue that only works on modified mainboards, not the stock ones.

**Comment by trashmaster9000** [comment]
ah, so there appears a button if i would flash _T or _TE firmware to the MB?

was a bit confused, since i didnt expect to accidentally find a hidden/disabled menu

**Comment by rommulaner** [comment]
Yes is should appear if you compile a version for TMC. It's like that since 6.1., so not defect.
