### ISSUE TITLE
"Load Factory Defaults" not working

### ISSUE THREAD

**Issue by trashmaster9000** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#6]
Hello,

after flashing the latest version i had way too high acceleration values on the axis setup. X/Y 5000mm/s2, Z 3000mm/s2 E 5000mm/s2

the button "Load Factory Default" doesn't do anything, it doesn't load the correct values and if i alter them they don't get changed back to these high values

**Comment by rommulaner** [comment]
These are the new settings that work on my Vyper. And yes, you cannot print all different walls with this settings as this settings are the max values the hardware can handle. For good prints you need to setup your slicer profile. These values are needed to be able to print fast when it is possible and to work with input shaping and bed mesh.

**Comment by rommulaner** [comment]
The Reset button works fine on my Vyper. Maybe you need to restart your printer as the values are saved in the screen cache.

**Comment by trashmaster9000** [comment]
just tested again:
set X acceleration to 5
go back, press load factory settings
go back to home screen
switch printer off, on
check x accleration again, still 5

**Comment by rommulaner** [comment]
You know that you need to hold the button 2 seconds until it beeps and shows the reset message?

**Comment by trashmaster9000** [comment]
now i know... 🤦
thanks!

didnt even know this display supports tap and hold.
kinda expected a confirmation dialog, maybe the one that appears when you print from sd-card could be repurposed for that?
