### ISSUE TITLE
Firmware flashed incorrectly

### ISSUE THREAD

**Issue by mat-pandaz** [rommulaner/Anycubic_Vyper_LCD_CE_6.1d#8]
Hi - It's flashing and I'm getting

CFG 001
CODE 002
BIN 003
DZK 000
HZK 001
ICL 006
the rest 000

It says process end on line 2, but it doesn't respond to any touch (I do it anyway).  Then when booting up the display it says community edition, I press on the screen and it goes to the main menu, then it says firmware flashed incorrectly.

I am using a 64gb SD with a single 8192MB partition @ 4096

The only difference between mine and the successful image is that CODE is giving 002 not 001 or 003.  Could it just be the SD card?

**Comment by rommulaner** [comment]
Mainboard and screen need to be flashed. 
You flashed the screen as I can see and when it says END! you just need to restart the printer, there is no possibility to click on anything.
As it says flashed incorrectly, you need to flash the mainboard. There is another repository for the MB.

**Comment by mat-pandaz** [comment]
That's got it thanks.

I didn't realise it was referring to the MB version.  The SD card I used to the motherboard wasn't flashing, but I used the same micro SD in an adapter that I used for the screen and worked straight away.

Thank you so much for the help and the software! All sorted now o>
